SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[uspListarMedicamento]
as
begin
select m.IIDMEDICAMENTO,m.NOMBREMEDICAMENTO,l.NOMBRE as NOMBRELABOTARIO,t.NOMBRE AS NOMBRETIPO
from  Medicamento m
inner join Laboratorio l
on m.IIDLABORATORIO=l.IIDLABORATORIO
inner join TipoMedicamento t
on m.IIDTIPOMEDICAMENTO=t.IIDTIPOMEDICAMENTO
where m.BHABILITADO=1
end
GO