SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[uspListarLaboratorio]
as
begin
select IIDLABORATORIO,NOMBRE,DIRECCION,PERSONACONTACTO
from Laboratorio
where BHABILITADO=1
---asasas
end
GO