CREATE TABLE [dbo].[Boton] (
  [IIDBOTON] [int] IDENTITY,
  [NOMBRE] [varchar](100) NULL,
  [IDBOTONPANTALLA] [varchar](100) NULL,
  [BHABILITADO] [int] NULL,
  CONSTRAINT [PK_Boton] PRIMARY KEY CLUSTERED ([IIDBOTON])
)
ON [PRIMARY]
GO