CREATE TABLE [dbo].[TipoMedicamento] (
  [IIDTIPOMEDICAMENTO] [int] IDENTITY,
  [NOMBRE] [varchar](100) NULL,
  [DESCRIPCION] [varchar](300) NULL,
  [BHABILITADO] [int] NULL,
  CONSTRAINT [PK_TipoMedicamento] PRIMARY KEY CLUSTERED ([IIDTIPOMEDICAMENTO])
)
ON [PRIMARY]
GO