CREATE TABLE [dbo].[Usuario] (
  [IIDUSUARIO] [int] IDENTITY,
  [NOMBREUSUARIO] [varchar](100) NULL,
  [IIDTIPOUSUARIO] [int] NULL,
  [CONTRA] [varchar](100) NULL,
  [BHABILITADO] [int] NULL,
  [IIDPERSONA] [int] NULL,
  CONSTRAINT [PK_Usuario] PRIMARY KEY CLUSTERED ([IIDUSUARIO])
)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[Usuario]
  ADD FOREIGN KEY ([IIDPERSONA]) REFERENCES [dbo].[Persona] ([IIDPERSONA])
GO

ALTER TABLE [dbo].[Usuario]
  ADD CONSTRAINT [FK_Usuario_TipoUsuario] FOREIGN KEY ([IIDTIPOUSUARIO]) REFERENCES [dbo].[TipoUsuario] ([IIDTIPOUSUARIO])
GO