CREATE TABLE [dbo].[Medicamento] (
  [IIDMEDICAMENTO] [int] IDENTITY,
  [CODIGO] [varchar](100) NULL,
  [NOMBREMEDICAMENTO] [varchar](100) NULL,
  [IIDLABORATORIO] [int] NULL,
  [BHABILITADO] [int] NULL,
  [IIDTIPOMEDICAMENTO] [int] NULL,
  [USOMEDICAMENTO] [varchar](300) NULL,
  [CONTENIDO] [varchar](300) NULL,
  CONSTRAINT [PK_Medicamento] PRIMARY KEY CLUSTERED ([IIDMEDICAMENTO])
)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[Medicamento]
  ADD CONSTRAINT [FK_Medicamento_Laboratorio] FOREIGN KEY ([IIDTIPOMEDICAMENTO]) REFERENCES [dbo].[TipoMedicamento] ([IIDTIPOMEDICAMENTO])
GO

ALTER TABLE [dbo].[Medicamento]
  ADD CONSTRAINT [FK_Medicamento_Laboratorio1] FOREIGN KEY ([IIDLABORATORIO]) REFERENCES [dbo].[Laboratorio] ([IIDLABORATORIO])
GO