CREATE TABLE [dbo].[Ingreso] (
  [IIDINGRESO] [int] IDENTITY,
  [IIDMEDICAMENTO] [int] NULL,
  [IIDLABORATORIO] [int] NULL,
  [FECHACOMPRA] [datetime] NULL,
  [CANTIDAD] [int] NULL,
  [FECHAVENCIMIENTO] [datetime] NULL,
  [PRECIOCOMPRA] [decimal](18, 2) NULL,
  [BHABILITADO] [int] NULL,
  [DFECHAVENCIMIENTO] [datetime] NULL,
  [IIDMARCA] [int] NULL,
  [PRECIOVENTA] [decimal](18, 2) NULL,
  [IIDENVOLTURA] [int] NULL,
  [IIDTIPOADMINISTRACION] [int] NULL,
  [FOTOMEDICAMENTO] [varbinary](max) NULL,
  [NOMBREFOTO] [varchar](100) NULL,
  CONSTRAINT [PK_Ingreso] PRIMARY KEY CLUSTERED ([IIDINGRESO])
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[Ingreso]
  ADD CONSTRAINT [FK_Ingreso_Envoltura] FOREIGN KEY ([IIDENVOLTURA]) REFERENCES [dbo].[Envoltura] ([IIDENVOLTURA])
GO

ALTER TABLE [dbo].[Ingreso]
  ADD CONSTRAINT [FK_Ingreso_Laboratorio] FOREIGN KEY ([IIDLABORATORIO]) REFERENCES [dbo].[Laboratorio] ([IIDLABORATORIO])
GO

ALTER TABLE [dbo].[Ingreso]
  ADD CONSTRAINT [FK_Ingreso_Marca] FOREIGN KEY ([IIDMARCA]) REFERENCES [dbo].[Marca] ([IIDMARCA])
GO

ALTER TABLE [dbo].[Ingreso]
  ADD CONSTRAINT [FK_Ingreso_Medicamento] FOREIGN KEY ([IIDMEDICAMENTO]) REFERENCES [dbo].[Medicamento] ([IIDMEDICAMENTO])
GO

ALTER TABLE [dbo].[Ingreso]
  ADD CONSTRAINT [FK_Ingreso_TipoAdministracion] FOREIGN KEY ([IIDTIPOADMINISTRACION]) REFERENCES [dbo].[TipoAdministracion] ([IIDTIPOADMINISTRACION])
GO