CREATE TABLE [dbo].[Sucursal] (
  [IIDSUCURSAL] [int] IDENTITY,
  [NOMBRE] [varchar](100) NULL,
  [DIRECCION] [varchar](300) NULL,
  [BHABILITADO] [int] NULL,
  [FOTOSUCURSAL] [varbinary](max) NULL,
  [NOMBREFOTOSUCURSAL] [varchar](100) NULL,
  CONSTRAINT [PK_Sucursal] PRIMARY KEY CLUSTERED ([IIDSUCURSAL])
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO