CREATE TABLE [dbo].[TipoDocumento] (
  [IIDTIPODOCUMENTO] [int] IDENTITY,
  [NOMBRE] [varchar](100) NULL,
  [BHABILITADO] [int] NULL,
  CONSTRAINT [PK_TipoDocumento] PRIMARY KEY CLUSTERED ([IIDTIPODOCUMENTO])
)
ON [PRIMARY]
GO